### PR TITLE
Changes Version of 'active_model_serializers' Dependency

### PR DESCRIPTION
**Pull request by DanielWright**
At present, `spree_wombat` depends on the 0.9.x branch of `active_model_serializers`. Development along this branch appears [to be defunct](https://github.com/rails-api/active_model_serializers#maintenance-please-read), with the rails-api team opting to work on an 0.10.x branch based off the 0.8.x branch. Phew, confusing!

Given the roadmap for AMS, I propose that it makes more sense to depend on the 0.8.x branch than the 0.9.x branch. This PR changes the version of `active_model_serializers` on which `spree_wombat` depends, and small changes to the serializers to keep the test suite green. My PR is targets the `2-4-stable` branch—please let me know if this maps to your contribution guidelines.

Looking forward to comments/feedback. Thanks!

### CODE REVIEW

**Comment by JDutil** [comment]
I think these changes are okay, but I'm not sure we should back port them.

**Comment by huoxito** [comment]
+1 for moving this to master only given everything we need is still working on 2-4-stable

**Comment by DanielWright** [comment]
I had based my changes on 2-4-stable, because I'm working on a storefront that uses 0.8.x. I will rebase to master for this PR, and maintain my own fork.

**Comment by JDutil** [comment]
Thanks @DanielWright

**Comment by DanielWright** [comment]
I'm closing this, as I can't change the branch being targetted.

**Pull request closed without merging**
