### PR TITLE
when taxons are not present, do not empty the products' taxon list

### PR DESCRIPTION
**Pull request by jao**
Hello,
using wombat I realized that when I removed the taxons value from my json payload, the product would end up with empty taxons after the update, because @taxon_ids would be empty.

Hope this helps.

### CODE REVIEW

**Comment by JDutil** [comment]
Why would you remove the taxons from the json payload?

**Comment by JDutil** [comment]
I'm going to close this out since I don't think it's an appropriate change.  Removing the taxons if none are provided is the expected behavior.

**Comment by JDutil** [comment]
Actually think I misunderstood this

**Comment by jao** [comment]
Passing empty taxons (taxons: []) and expecting them to be removed I can understand, but if I remove the "taxons" property altogether seems a bit silly, since it seems they are not required.
And by doing so I could prevent unneeded changes from propagating.

In my case, it is where I'm getting most of my mysql deadlocks.

**Comment by jao** [comment]
oh, also, I forgot one thing:

diff --git a/lib/spree/wombat/handler/product_handler_base.rb b/lib/spree/wombat/handler/product_handler_base.rb
index c176484..a964587 100644
--- a/lib/spree/wombat/handler/product_handler_base.rb
+++ b/lib/spree/wombat/handler/product_handler_base.rb
@@ -5,7 +5,7 @@ module Spree
     module Handler
       class ProductHandlerBase < Base
 
-        attr_accessor :params, :children_params, :master_images, :taxons, :taxon_ids,
+        attr_accessor :params, :children_params, :master_images, :taxons_list, :taxon_ids,
                       :root_options, :properties
 
         def initialize(message)

**Pull request closed without merging**
